keys:
  - &makefu F7B8DCE46BC6B0A8F95477C8563B8DFE2A0E2029
  - &x_host age1hqe5hs2jz2fk5zvw346ajhwlagkheunacahpu42uruxu0nlnwy7qn9q5k6
  - &tsp_host age1p7jqdpahxtf7j70kmzy7vg6za7wg63u6sq7ywuw6qkw0qek395nq5kyzae
  - &gum_host age13ekyvn5ux7zyvclwlrpnhgauw5s6dzn538msjka8vpwhu535ychqa7dk7a
  - &omo_host age1g0h4fhgnfr7zvp3mqa32u24k4nlfpqmk4dvl5pwnj7t3m6zl2cfs3mw7ht
  - &wbob_host age1fz3fm09mpur0r5pp43tyuzemkx3f0gfwtgfxj6usv28apq8pfc6qnw3z2s
  - &cake_host age12xhv7z8w3zaq2c0mf940a8afnardplye9fd6p2m5ynnck3k7vd7q00sqjy
  - &savarcast_host age1x98njnqerw9nw9pzud4h6tjqqtxdmw0ugqry8uehnflk24d023tqrsuf0f
  - &filepimp_host age1evnvl9r8x7dxpm8u5uea6jxhyhhr3j3l4nlypvy5sjpcrrp3rdsq4ytkk0
creation_rules:
  - path_regex: secrets/common.yaml$
    key_groups:
    - pgp:
      - *makefu
      age:
      - *tsp_host
      - *savarcast_host
      - *x_host
      - *wbob_host
      - *cake_host
      - *omo_host
      - *gum_host
  # host secrets
  - path_regex: secrets/filepimp.yaml$
    key_groups:
    - pgp:
      - *makefu
      age:
      - *filepimp_host
  - path_regex: secrets/x.yaml$
    key_groups:
    - pgp:
      - *makefu
      age:
      - *x_host
  - path_regex: secrets/tsp.yaml$
    key_groups:
    - pgp:
      - *makefu
      age:
      - *tsp_host
  - path_regex: secrets/savarcast.yaml$
    key_groups:
    - pgp:
      - *makefu
      age:
      - *savarcast_host
  - path_regex: secrets/gum.yaml$
    key_groups:
    - pgp:
      - *makefu
      age:
      - *gum_host
  - path_regex: secrets/torrent.yaml$
    key_groups:
    - pgp:
      - *makefu
      age:
      - *gum_host
      - *omo_host
  - path_regex: secrets/omo.yaml$
    key_groups:
    - pgp:
      - *makefu
      age:
      - *omo_host
  - path_regex: secrets/wbob.yaml$
    key_groups:
    - pgp:
      - *makefu
      age:
      - *wbob_host
  - path_regex: secrets/cake.yaml$
    key_groups:
    - pgp:
      - *makefu
      age:
      - *cake_host
